//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: SN.withSIX.Core.Applications.Attributes.ToolsVersionAttribute("2.3")]

// Generated by the MSBuild WriteCodeFragment class on 13-11-2015 10:20:32.

